package com.glance.parcel.platform.paper.bootstrap;

import com.google.gson.Gson;
import io.papermc.paper.plugin.loader.PluginClasspathBuilder;
import io.papermc.paper.plugin.loader.PluginLoader;
import io.papermc.paper.plugin.loader.library.LibraryLoadingException;
import io.papermc.paper.plugin.loader.library.impl.MavenLibraryResolver;
import org.eclipse.aether.artifact.DefaultArtifact;
import org.eclipse.aether.graph.Dependency;
import org.eclipse.aether.repository.RemoteRepository;

import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

/**
 * Resolves the plugin's runtime libraries from the {@code paper-libraries.json} generated by
 * plugin-yml, instead of shading them into the jar.
 *
 * <p>Deliberately written in Java: this runs <em>before</em> the libraries it is resolving are on
 * the classpath, and kotlin-stdlib is one of those libraries. A Kotlin loader would fail to load
 * itself.
 */
public final class ParcelLibLoader implements PluginLoader {

    @Override
    public void classloader(PluginClasspathBuilder classpathBuilder) {
        MavenLibraryResolver resolver = new MavenLibraryResolver();
        PluginLibraries libs = load();

        libs.dependencies().forEach(dependency ->
            resolver.addDependency(new Dependency(new DefaultArtifact(dependency), null)));

        libs.repositories().forEach((id, url) ->
            resolver.addRepository(new RemoteRepository.Builder(id, "default", url).build()));

        classpathBuilder.addLibrary(resolver);
    }

    private PluginLibraries load() {
        try (var in = getClass().getResourceAsStream("/paper-libraries.json")) {
            if (in == null) {
                throw new IllegalStateException("paper-libraries.json is missing from the jar");
            }
            return new Gson().fromJson(
                new InputStreamReader(in, StandardCharsets.UTF_8),
                PluginLibraries.class);
        } catch (Exception e) {
            throw new LibraryLoadingException("Failed to load Parcel's runtime libraries", e);
        }
    }

    private record PluginLibraries(
        Map<String, String> repositories,
        List<String> dependencies
    ) {
    }
}
